### ISSUE TITLE
windows 10 - annotator workers failed to resolve broker hostname

### ISSUE THREAD

**Issue by ieriii** [jsbroks/coco-annotator#488]
I'm trying to use the coco-annotator on my windows 10 laptop. 
When I run `docker-compose up`, the container fails to run properly. The error:
```
consumer: Cannot connect to amqp://user:**@messageq:5672//: failed to resolve broker name hostname.
```

Anyone has any suggestions on how to fix this?
I also tried to run the container from WSL2 but no luck.

**Comment by rochimfn** [comment]
The problem is caused by the new version of RabbitMQ won't running while using deprecated `RABBITMQ_DEFAULT_PASS` and `RABBITMQ_DEFAULT_USER` environment variables (Refer: [https://hub.docker.com/_/rabbitmq](https://hub.docker.com/_/rabbitmq) Environment Variables section). 
You can try to downgrade the version of RabbitMQ by changing the image version to 3.8 in `docker-compose.yml` file.

```yaml
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - cocoannotator
```

to

```yaml
  messageq:
    image: rabbitmq:3.8
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - cocoannotator
```

Hope it helps
